### ISSUE TITLE
what is the meaning of the red color and underline?

### ISSUE THREAD

**Issue by Cherry0809** [angusmoore/tvarGIRF#6]
Hi~Moore.Thank you for your related work on GIRF of TVAR. I have some question about the result. And I would appreciate it if you could reply.
After I run the following code
   library(tsDyn)
   library(tvarGIRF)
   data(zeroyld)
   exampleTVAR <- TVAR(zeroyld, lag=2, nthresh=1, thDelay=1, mTh=1, plot=FALSE)
    girf_full <- GIRF(exampleTVAR4, c(0,1), horizon =10, H = 10, R = 50,restrict.to =NA )
    girf_full[["responses"]]

the results show:

 short.run long.run
       <dbl>    <dbl>
 1  -0.00493    0.996
 2   0.0380     0.954
 3   0.0105     0.888
 4   0.0381     0.849
 5   0.0828     0.831
 6   0.110      0.799
 7   0.126      0.795
 8   0.105      0.729
 9   0.131      0.671
10   0.142      0.643

 The color of number " -0.00493"  is red. And there are some  underlines in the last number of "-0.00493"、“0.0380”、“0.0380”、“0.0380”、“0.0828”. What is the meaning of the red color and these underlines? Does these indicate the negtive number and  redundant  fractional parts ?

**Comment by angusmoore** [comment]
Hi Cherry,

The printing you see is the default printing for a [tibble](https://tibble.tidyverse.org/), which is what the GIRF results are returned in. `tibble`s are a type of `data.frame` that have nicer default printing methods (and some other features). The red simply means the number is negative, and underlining is used for any digit four or more places from the decimal point (to try to help show magnitudes).

This is a feature of `tibble`s, not of `tvarGIRF`. You can print it as a regular dataframe, without the colours and underlining by doing:
```
as.data.frame(girf_full[["responses"]])
```

Hope that helps.

**Comment by Cherry0809** [comment]
Thank you for your kind reply. It's really helpful.
Best Regards !
